/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.multiwarehouse.app.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum SellerOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<SellerOrderStatus> {
  PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SellerOrderStatus\",\"namespace\":\"com.multiwarehouse.app.kafka.order.avro.model\",\"symbols\":[\"PAID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
